version: '3.7'
services:
  app:  
    build: ./Frontend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "production"
      SERVER_URL: "54.227.120.82"
      SERVER_PORT: "3002"
    links:
      - server
  server:
    build: ./Backend
    links:
      - db
    ports:
      - 3002:3002
    environment:
      NODE_ENV: "production"
      PORT: "3002"
      SQL_PORT: "3306"
      SQL_HOST: "db"
      SQL_USER: "root"
      SQL_PASSWORD: ""
      SQL_DATABASE: "bynet"
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "bynet"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - mysql-data:/var/lib/mysql
    - ./Database/bynet.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-data:
    driver: local